### ISSUE TITLE
Installation fails due to permission denied error

### ISSUE THREAD

**Issue by anglinb** [probot/create-probot-plugin#5]
👋 I ran into an error using the `create-probot-plugin` cli interface. I've included details below--I haven't take the time to try and track down to root cause but running as `root` fixes the issue. 🙃 

**Steps to reproduce:**
1. `npm install -g create-probot-plugin`
2. `create-probot-plugin express-example`

**Error Traceback**

```
Let's create a Probot plugin!
? Plugin's package name: express-example
? Description of plugin: An example of how to use express in a probot plugin
? Plugin author's full name: Brian Anglin
? Plugin author's email address: banglin@usc.edu
? Plugin author's homepage: https://github.com/anglinb
? Plugin's GitHub user or org name: anglinb
? Plugin's repo name: express-example
fatal: could not create leading directories of '/Users/brian/.cache/.egad-templates/https-github-com-probot-plugin-template-git': Permission denied

(node:74816) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): fatal: could not create leading directories of '/Users/brian/.cache/.egad-templates/https-github-com-probot-plugin-template-git': Permission denied

(node:74816) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bkeepers** [comment]
> fatal: could not create leading directories of '/Users/brian/.cache/.egad-templates/https-github-com-probot-plugin-template-git': Permission denied

@anglinb weird, looks like permissions are wrong on something in `/Users/brian/.cache/` (maybe from running something with `sudo` in the past, which would have created this directory with the wrong permissions?). You might want to try just renaming that directory and running it again.

**Comment by anglinb** [comment]
Hmm good thought 🤔 `/Users/brian/.cache` was owned by root and I changed it to my user that seemed to fix it. Thanks for the help--I'm sure I installed something as root once and that changed it. 🙃
